### ISSUE TITLE
strlcpy not found

### ISSUE THREAD

**Issue by eddavis2** [ibara/edx#1]
When I tried to compile this on Ubuntu-22.04, I got an error about not finding strlcpy.
Found that it was in a library - libbsd.
I installed libbsd-dev, and changed the makefile, adding "-lbsd" to the link line.
Now it compiles!
Thanks for sharing edx!

**Comment by ibara** [comment]
The strl* family is from OpenBSD, and is included in all major libc implementations. After 25 years, it has finally been added to glibc, so you may need to update your glibc.

**Comment by eddavis2** [comment]
Yep, I just read where it got added to glibc in literally just the last few weeks.
It is now in glibc version 2.38.

My problem is that I'm using the latest of Ubuntu - and it still includes glibc 2.35, which does not include strlcpy.

Hopefully Ubuntu will be updated soon to have the latest glibc.

In the meantime, adding libbsd worked a treat!

--
On Friday, August 11, 2023 at 09:28:15 PM EDT, Brian Callahan ***@***.***> wrote: 

The strl* family is from OpenBSD, and is included in all major libc implementations. After 25 years, it has finally been added to glibc, so you may need to update your glibc.
